[project]
name = "daytwo-ii"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies =   [
    "fastapi",
    "uvicorn",
    "langchain-groq",
    "langchain-core",
    "python-dotenv",
    "langchain-qdrant",
    "langchain-huggingface",
    "sentence-transformers",
    "grpcio>=1.83.0",
]
